### ISSUE TITLE
Use latest stockfish dev

### ISSUE THREAD

**Issue by barca-cloud** [LichessBot-Coders/Lichess-Coded-Bot#8]
Use the latest with a new nnue

**Comment by SathyaKarthik1212** [comment]
Latest Engine?

**Comment by barca-cloud** [comment]
> This repo is already using Latest Stockfish DEV
> Ask VigneshUltimate to update to NNUE

Well i cant ask as i am not in lichess nad there is a new engine

**Comment by SathyaKarthik1212** [comment]
Which new engine

**Comment by barca-cloud** [comment]
Also add me a  collabrator i will help and close #7

**Comment by barca-cloud** [comment]
> Which new engine
Stockfish dev (new)

**Comment by SathyaKarthik1212** [comment]
He should change it in config.yml in his repo not here

**Comment by barca-cloud** [comment]
> He should change it in config.yml in his repo not here

So close #7 it not helpfull or add me me as a contributor

**Comment by barca-cloud** [comment]
> He should change it in config.yml in his repo not here

You made me a collabarator?

**Comment by SathyaKarthik1212** [comment]
> > He should change it in config.yml in his repo not here
> 
> You made me a collabarator?

No
